### ISSUE TITLE
getBatteryLevel & isCharging don't update result

### ISSUE THREAD

**Issue by nivnahmias** [robinpowered/react-native-device-battery#13]
Calling the 2 main functions getBatteryLevel & isCharging don't change result after the first call.
For example, calling isCharging when the phone is connected will return true, disconnecting the phone and calling the function again will still return true.

Using the listener the disconnect event is captured but i would prefer to just use the 2 functions.
I'm not sure what's causing this issue.

Thanks

**Comment by nivnahmias** [comment]
Looking at the native code in [here](https://github.com/robinpowered/react-native-device-battery/blob/master/android/src/main/java/com/robinpowered/react/battery/DeviceBatteryModule.java#L60) it seems "batteryStatus" doesn't get updated ever, is this possibly causing this issue where the data received from it isn't changing? Perhaps "notifyBatteryStateChanged" should be changing the value of "batteryStatus" with its new Intent argument?

**Comment by nivnahmias** [comment]
I checked my suggestion locally and that seemed to fix the issue, i added a pull request for fix

**Comment by atticoos** [comment]
Thanks @nivnahmias!
