### ISSUE TITLE
removeListener method missing

### ISSUE THREAD

**Issue by ascorbic** [robinpowered/react-native-device-battery#20]
Hi
The docs refer to `DeviceBattery.removeListener(onBatteryStateChanged);`, but this method seems to be missing from the code and throws a TypeError.

**Comment by ascorbic** [comment]
Just saw that there's an outstanding PR #18 that adds this. Could this be merged and updated?

**Comment by SirKadogan** [comment]
Yep, that commit fixes it. Any updates on when this will be merged? @christophermark

**Comment by jutaz** [comment]
#18 was merged and released as part of https://github.com/robinpowered/react-native-device-battery/releases/tag/v2.1.0
