### ISSUE TITLE
getBatteryLevel doesn't get an updated battery level on Android

### ISSUE THREAD

**Issue by madwed** [robinpowered/react-native-device-battery#3]
Hey guys,

I've been trying to use your library to take snapshots of a device's battery drain while apps are running in the background on Android.  Unfortunately, it seems that `.getBatteryLevel()` doesn't return an updated battery level even when called 30-60 minutes later with clear battery loss of 4-5%.  I'm keeping the app in the foreground, so I don't think that background state would be an issue.

I noticed that `Intent.ACTION_BATTERY_CHANGED` is a sticky intent, so I thought that the sticky intent caching values could be the issue.  I tried adding changing `public void getBatteryLevel(Promise promise) to:

```
public void getBatteryLevel(Promise promise) {
   if (batteryStatus != null) {
      float batteryPercentage = getBatteryPrecentageFromIntent(batteryStatus);
      promise.resolve((double) batteryPercentage);

      getReactApplicationContext().removeStickyBroadcast(batteryStatus);
      IntentFilter filter = new IntentFilter(Intent.ACTION_BATTERY_CHANGED);
      batteryStatus = getReactApplicationContext().registerReceiver(batteryStateReceiver, filter);
   } else {
      promise.reject("Battery manager is not active");
   }
}
```

I was hoping that removing the intent and reregistering it would invalidate the cache, but it seems it doesn't or that this is not the source of the problem.

The only way I could get `getBatteryLevel()` to detect a new value was by closing the app and reinstalling or by reloading the JS.  Even by doing this I could only get `getBatteryLevel()` to return a new value when there was a significant change (from .28000000011920929 to .28999999165534973), but finer grained changes were impossible to detect.

I'm aware that this may be an Android API problem and not a problem with your code.  Have you had any experience dealing with this kind of issue?

Thanks!

**Comment by madwed** [comment]
After digging into the  `BatteryManager` API a bit more I'm seeing that it just isn't possible to get that fine grained results from the device.  All of the `BatteryManager` intents and constants return `int`s or `long`s when plugged into the appropriate methods.  Maybe it would be more accurate to return a fixed point number from `getBatteryLevel()` to make the lack of precision clearer?  If so I can put in a PR with the change.

**Comment by atticoos** [comment]
>  Unfortunately, it seems that `.getBatteryLevel()` doesn't return an updated battery level even when called 30-60 minutes later with clear battery loss of 4-5%. I'm keeping the app in the foreground, so I don't think that background state would be an issue.

So on the UI side of things you weren't seeing that 4-5% change coming through? Even while the application was foregrounded?

**Comment by madwed** [comment]
That's right.  

I'm doing another test right now that should check the battery change over the course of 3 hours.  I'll update you whether or not I see any change when it's finished.

**Comment by atticoos** [comment]
Sounds good, I'll give this a look as well - I don't think we've experienced this.

**Comment by madwed** [comment]
After the 3 hour test, I am seeing the battery level go down.  Not sure what happened during the first test.  Everything looks good, thanks for your help!

**Comment by atticoos** [comment]
That's good to hear 😄  Glad it's workin for ya
