### ISSUE TITLE
Publish recent improvements to npm

### ISSUE THREAD

**Issue by fagerbua** [robinpowered/react-native-device-battery#5]
Thanks for providing this useful module. I noticed that the [npm package](https://www.npmjs.com/package/react-native-device-battery) was last updated 9 months ago, whereas several improvements have been commited to this repository more recently. May I suggest you publish a new version to the npm?

**Comment by atticoos** [comment]
Sure thing @fagerbua. Thanks for the bump - I'll determine the proper versioning and aim to get the updated version published soon 😄 

Once published, I will follow up on this thread.

**Comment by st0ffern** [comment]
@ajwhite why not use commitizen and semantic-release for automatic versioning, version notes, and npm publising ?

**Comment by natterstefan** [comment]
Hi @ajwhite, so is the current version here on GitHub also on npm?

**Comment by atticoos** [comment]
Hey @natterstefan -- we have a couple PRs that will be coming in this week and we'll be publishing in a couple days

**Comment by natterstefan** [comment]
@ajwhite sounds great, thank you!

**Comment by nivnahmias** [comment]
Any update on this? We can't use the module because of the missing Activity constructor argument

**Comment by atticoos** [comment]
`v1.0.0` has now been published to NPM
